name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
      - master
    paths:
      - .bumpversion.cfg

jobs:
  release:
    uses: plus3it/actions-workflows/.github/workflows/release.yml@8f8c209f4baa89f8b624937368ed36646313e987
    secrets:
      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
    with:
      mockstacktest-pytest-args: -v -k 'not create_request_payment and not create_intelligent_tiering and not create_inventory and not create_lifecycles'
