name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
      - master
    paths:
      - .bumpversion.cfg

jobs:
  release:
    uses: plus3it/actions-workflows/.github/workflows/release.yml@84885d2116bdcaab046d6bf927127bb58cb74ae8
    secrets:
      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
    with:
      mockstacktest-pytest-args: -v -k 'not create_inventory'
